CSK_FILTERS = {'mnist': 31,
               'fmnist': 31,
               'cifar10': 41,
               'cifar100': 41,
               'nist': 640,
               }
CSK_KERNELS = {'mnist': 5,
               'fmnist': 5,
               'cifar10': 5,
               'cifar100': 5,
               'nist': 5,
               }
CLK_FILTERS = {'mnist': 8,
               'fmnist': 8,
               'cifar10': 12,
               'cifar100': 12,
               'nist': 2,
               }
CLK_KERNELS = {'mnist': 21,
               'fmnist': 21,
               'cifar10': 17,
               'cifar100': 17,
               'nist': 34,
               }

# for no absolute calculation
aCSK_FILTERS = {'mnist': 31,
                'fmnist': 31,
                'cifar10': 41,
                'cifar100': 41,
                'nist': 640,
                'scenes': 900,
                'blood': 950,
                }
aCSK_KERNELS = {'mnist': 5,
                'fmnist': 5,
                'cifar10': 5,
                'cifar100': 5,
                'nist': 5,
                'scenes': 5,
                'blood': 9,
                }
aCLK_FILTERS = {'mnist': 16,
                'fmnist': 16,
                'cifar10': 20,
                'cifar100': 24,
                'nist': 4,
                'scenes': 10,
                'blood': 12,
                }
aCLK_KERNELS = {'mnist': 21,
                'fmnist': 21,
                'cifar10': 17,
                'cifar100': 17,
                'nist': 34,
                'scenes': 32,
                'blood': 81,
                }

# for train imaginary, no abs
iCSK_FILTERS = {'mnist': 62,
                'fmnist': 62,
                'cifar10': 82,
                'cifar100': 82,
                'nist': 1261,
                }
iCSK_KERNELS = {'mnist': 5,
                'fmnist': 5,
                'cifar10': 5,
                'cifar100': 5,
                'nist': 5,
                }
iCLK_FILTERS = {'mnist': 16,
                'fmnist': 16,
                'cifar10': 20,
                'cifar100': 20,
                'nist': 4,
                }
iCLK_KERNELS = {'mnist': 21,
                'fmnist': 21,
                'cifar10': 17,
                'cifar100': 17,
                'nist': 34,
                }

BASELINES = {'mnist': 0.80,
             'fmnist': 0.75,
             'cifar10': 0.30,
             'cifar100': 0.10,
             'nist': 0.01,
             'blood': 0.01,
             'scenes': 0.01,
             }

BUILD = {'mnist': {'input_shape': (28, 28, 1),
                   'noof_classes': 10,
                   },
         'fmnist': {'input_shape': (28, 28, 1),
                    'noof_classes': 10,
                    },
         'cifar10': {'input_shape': (32, 32, 3),
                     'noof_classes': 10,
                     },
         'cifar100': {'input_shape': (32, 32, 3),
                      'noof_classes': 100,
                      },
         'nist': {'input_shape': (128, 128, 1),
                  'noof_classes': 10,
                  },
         'blood': {'input_shape': (320, 240, 3),
                   'noof_classes': 4,
                   },
         'scenes': {'input_shape': (150, 150, 3),
                    'noof_classes': 6,
                    },
         }
COMPILE = {'optimizer': 'adam',
           'loss': 'categorical_crossentropy',
           'metrics': [],
           'run_eagerly': False,
           }
TRAIN = {'epochs': 100,
         'batch': 8,
         'validation_split': 0.2,
         'verbose': 1,
         'call_time': True,
         'call_stop': True,
         'call_stop_kwargs': {'baseline': 0.90,
                              'monitor': 'val_categorical_accuracy',
                              'patience': 2,
                              },
         'call_checkpoint': False,
         # 'call_checkpoint_kwargs': {'monitor': 'val_categorical_accuracy',
         #                            },
         }